### ISSUE TITLE
[rocket::config::error][ERROR] I/O error while setting tls.certs

### ISSUE THREAD

**Issue by Doceran** [dani-garcia/bitwarden_rs#1028]
Hi Guys.

I'm actually trying to install my own local bitwardenrs server on a raspberry Pi3.
this server will be available only from my LAN and it won't be open to WAN.
i want to create volumes to my NAS to be able to save the files in case i delete the container.

Actually the volumes are working because i can see the files in the different folders and i also got other containers like pi-hole and wordpress working correcty.

i did many attempts but i always got the same error : "[rocket::config::error][ERROR] I/O error while setting tls.certs" and the container is rebboting again and again.

First i tried with this compose file : 

```
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:raspberry
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: 'true'
      ROCKET_TLS: '{certs="/ssl/bitwarden.crt",key="/ssl/bitwarden.key"}'
      LOG_FILE: '/data/bitwarden.log'
      SIGNUPS_ALLOWED: 'true'
      DATABASE_URL: '/database/bitwarden.sqlite3'
      ATTACHMENTS_FOLDER: '/attachments'
      DATA_FOLDER: '/persistent'
      ICON_CACHE_FOLDER: '/icon_cache'
    volumes:
      - bw-data:/persistent
      - bw-database:/database
      - bw-attachments:/attachments
      - ssl:/ssl
      - icon_cache:/icon_cache
    ports:
      - 8000:80
    networks:
      - bitwarden-network
volumes:
 bw-data:
  driver: local
  driver_opts:
   type: nfs
   o: addr=192.168.**.**,rw,nolock
   device: ":/****/****/bitwarden/Raspberry-PI/bw-data"
 bw-database:
  driver: local
  driver_opts:
   type: nfs
   o: addr=192.168.**.**,rw,nolock
   device: ":/****/****/bitwarden/Raspberry-PI/bw-database"
 ssl:
  driver: local
  driver_opts:
   type: nfs
   o: addr=192.168.**.**,rw,nolock
   device: ":/****/****/bitwarden/Raspberry-PI/ssl"
 icon_cache:
  driver: local
  driver_opts:
   type: nfs
   o: addr=192.168.**.**,rw,nolock
   device: ":/****/****/bitwarden/Raspberry-PI/icon_cache"
 bw-attachments:   
  driver: local
  driver_opts:
   type: nfs
   o: addr=192.168.**.**,rw,nolock
   device: ":/****/****/bitwarden/Raspberry-PI/bw-attachments"
networks:
 bitwarden-network:
  driver: bridge
  ipam:
   config:
    - subnet: 172.23.4.0/29
```

Then i searched for some help about this error and i saw this issue :  https://github.com/dani-garcia/bitwarden_rs/issues/806#issue-546060510

so i tried to make a test with this code : 

`docker run -d --name='bitwarden' -e 'SIGNUPS_ALLOWED'='true' -e ROCKET_TLS='{certs="/ssl/bitwarden.crt",key="/ssl/bitwarden.key"}' -p 8343:80/tcp -v /root/bitwarden/test/:/data/:rw -v /root/bitwarden/test/:/ssl/ bitwardenrs/server:raspberry`

it didn't work and i got the same error.

i did many tests with my own openssl certificate and i also tried this one : https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome

Do you have any idea where this error comes from ?
Please help me, thx
