### ISSUE TITLE
Logout when importing/moving items

### ISSUE THREAD

**Issue by jostyee** [dani-garcia/bitwarden_rs#1035]
### Subject of the issue
With the latest version of bitwarden_rs, when I importing multiple items from 1Password or move them to another folder, sometimes the web vault would auto logout.

### Your environment
* Bitwarden_rs version: 
```
Server Installed Ok
    1.15.1-a87646b8 
Server Latest
    1.15.1-a87646b8 
Web Installed Ok
    2.14.0 
Web Latest
    2.14.0 
```

* Install method: Docker image
* Clients used: Firefox/Safari browser
* Reverse proxy and version: Synology Application portal
* Version of mysql/postgresql: SQLite 3.10.2
* Other relevant information: 

### Steps to reproduce
export several items from 1Password, import into bitwarden or move some existing ones to another folder.

my docker-compose.yml

```
---
version: "3.7"

services:
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    restart: unless-stopped
    user: 1029:100
    environment:
      - PUID=1029
      - PGID=100
      - TZ=Asia/Singapore
      - ENABLE_DB_WAL=false
      - ADMIN_TOKEN=***
      - INVITATIONS_ALLOWED=true
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - DOMAIN=https://vault.domain.com
      - WEBSOCKET_ENABLED=true
      - WEBSOCKET_ADDRESS=0.0.0.0
      - WEBSOCKET_PORT=3012
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ROCKET_ENV=production
      - ROCKET_PORT=8081
      - ROCKET_WORKERS=10
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=***
      - SMTP_FROM_NAME=Bitwarden_RS
      - SMTP_PORT=465
      - SMTP_EXPLICIT_TLS=true
      - SMTP_SSL=true
      - SMTP_USERNAME=***
      - SMTP_PASSWORD=***
      - SMTP_AUTH_MECHANISM="Plain"
      - SMTP_TIMEOUT=15
      - YUBICO_CLIENT_ID=***
      - YUBICO_SECRET_KEY=***
    volumes:
      - ./bw-data/:/data
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - 8080:8080
      - 3012:3012
```

### Expected behaviour
kept logged in

### Actual behaviour
bitwarden web logged out automatically

### Relevant logs
```
[2020-06-19 06:46:12][request][INFO] PUT /api/ciphers/move
[2020-06-19 06:46:13][request][INFO] GET /api/ciphers/1***e
[2020-06-19 06:46:13][auth][ERROR] Unauthorized Error: Invalid device id
[2020-06-19 06:46:13][response][INFO] GET /api/ciphers/<uuid> (get_cipher) => 401 Unauthorized
[2020-06-19 06:46:13][response][INFO] PUT /api/ciphers/move (move_cipher_selected_put) => 200 OK
```
