### ISSUE TITLE
Login on Admin Panel redirects to localhost

### ISSUE THREAD

**Issue by tschoesi** [dani-garcia/bitwarden_rs#1068]
Hi there

I'm experiencing an issue where trying to log in via the admin panel redirects to `localhost/admin`.

I am using `Traefik` as a reverse proxy and `docker-compose` on a raspberry pi 4.

My docker-compose:
(`[domain]` and `[myAdminToken]` are set to my domain and admin token)
```
---
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:raspberry
    container_name: bitwarden
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/bitwarden:/data
    environment:
      - ADMIN_TOKEN=[myAdminToken]
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bitwarden-https.redirectscheme.scheme=https"
      - "traefik.http.routers.bitwarden-http.entrypoints=web"
      - "traefik.http.routers.bitwarden-http.rule=Host(`bitwarden.[domain.com]`)"                 
      - "traefik.http.routers.bitwarden-http.middlewares=bitwarden-https@docker"
      - "traefik.http.routers.bitwarden.entrypoints=web-secure"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.[domain].com`)"                 
      - "traefik.http.routers.bitwarden.tls=true"
#      - "traefik.http.routers.bitwarden.tls.certresolver=default"
      - "traefik.http.routers.bitwarden.middlewares=secHeaders@file"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
```

Any ideas on how I can fix this?
Everything else works fine.

Thanks! :)
