### ISSUE TITLE
[SOLVED] Master Password suddenly stops working

### ISSUE THREAD

**Issue by NothingWorksToday** [dani-garcia/bitwarden_rs#1097]
### Subject of the issue

Yesterday or so my Bitwarden-Setup broke, so today I tried to fix it. 
The server does not accept my Master Password.

### Your environment

* Bitwarden_rs version: 1.16.3

* Install method: pulled from Docker Hub
* Clients used: FF extension, Android App, Webpage
* Reverse proxy and version: Traefik 2.0
* Version of mysql/postgresql: 
* Other relevant information: 

### Steps to reproduce

Running
```
sudo docker-compose up   
Creating bitwarden ... done
Attaching to bitwarden
bitwarden    | /--------------------------------------------------------------------\
bitwarden    | |                       Starting Bitwarden_RS                        |
bitwarden    | |                      Version 1.13.1-632d5526                       |
bitwarden    | |--------------------------------------------------------------------|
bitwarden    | | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
bitwarden    | | official channels to report bugs/features, regardless of client.   |
bitwarden    | | Report URL: https://github.com/dani-garcia/bitwarden_rs/issues/new |
bitwarden    | \--------------------------------------------------------------------/
bitwarden    | 
bitwarden    | [2020-08-13 19:31:31][start][INFO] Rocket has launched from http://0.0.0.0:80
```
looked OK but didn't let me log in.
So I updated the image with 
```
sudo docker pull bitwardenrs/server:alpine
alpine: Pulling from bitwardenrs/server
cbdbe7a5bc2a: Already exists 
faa145b85451: Pull complete 
699b3060ca80: Pull complete 
9b81b7bdc9c5: Pull complete 
c9f59281b5c2: Pull complete 
98018d0b77a4: Pull complete 
d4d6f4485843: Pull complete 
f9c51b50e882: Pull complete 
Digest: sha256:4022dc7efc1cdef9e855c94100b913a49204d797644216b0b1e5ca647c2b5099
Status: Downloaded newer image for bitwardenrs/server:alpine
docker.io/bitwardenrs/server:alpine
```
Now when logging in i get
```
sudo docker-compose logs bitwarden
[sudo] Passwort für jared: 
Attaching to bitwarden
bitwarden    | /--------------------------------------------------------------------\
bitwarden    | |                       Starting Bitwarden_RS                        |
bitwarden    | |                           Version 1.16.3                           |
bitwarden    | |--------------------------------------------------------------------|
bitwarden    | | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
bitwarden    | | official channels to report bugs/features, regardless of client.   |
bitwarden    | | Send usage/configuration questions or feature requests to:         |
bitwarden    | |   https://bitwardenrs.discourse.group/                             |
bitwarden    | | Report suspected bugs/issues in the software itself at:            |
bitwarden    | |   https://github.com/dani-garcia/bitwarden_rs/issues/new           |
bitwarden    | \--------------------------------------------------------------------/
bitwarden    | 
bitwarden    | Running migration 20200313205045
bitwarden    | Running migration 20200409235005
bitwarden    | Running migration 20200701214531
bitwarden    | [2020-08-13 19:39:03.619][start][INFO] Rocket has launched from http://0.0.0.0:80
bitwarden    | [2020-08-13 19:44:46.566][request][INFO] POST /api/accounts/prelogin
bitwarden    | [2020-08-13 19:44:46.566][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK
bitwarden    | [2020-08-13 19:44:46.796][request][INFO] POST /identity/connect/token
bitwarden    | [2020-08-13 19:44:46.796][error][ERROR] Username or password is incorrect. Try again. IP: 162.158.94.87. Username: MAIL.
bitwarden    | [2020-08-13 19:44:46.796][response][INFO] POST /identity/connect/token (login) => 400 Bad Request
bitwarden    | [2020-08-13 19:44:55.220][request][INFO] POST /api/accounts/prelogin
bitwarden    | [2020-08-13 19:44:55.220][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK
bitwarden    | [2020-08-13 19:44:55.402][request][INFO] POST /identity/connect/token
bitwarden    | [2020-08-13 19:44:55.402][error][ERROR] Username or password is incorrect. Try again. IP: 162.158.94.87. Username: MAIL.
bitwarden    | [2020-08-13 19:44:55.402][response][INFO] POST /identity/connect/token (login) => 400 Bad Request
bitwarden    | [2020-08-13 19:45:27.196][request][INFO] POST /api/accounts/prelogin
bitwarden    | [2020-08-13 19:45:27.196][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK
bitwarden    | [2020-08-13 19:45:27.340][request][INFO] POST /identity/connect/token
bitwarden    | [2020-08-13 19:45:27.341][error][ERROR] Username or password is incorrect. Try again. IP: 162.158.94.87. Username: MAIL.
bitwarden    | [2020-08-13 19:45:27.341][response][INFO] POST /identity/connect/token (login) => 400 Bad Request
```
And before you ask: The PW is correct, I typed it in often enough ;)

### Expected behaviour

Login

### Actual behaviour

No Login.
+ In the App I cannot view my vault - it's like the vault was empty...
 Other services from my setup work perfectly fine, so it is not Traefik

### Logs or Configs
```
cat docker-compose.yml 
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:alpine
    container_name: bitwarden
    restart: always
    volumes:
      - /mnt/data-storage/bitwarden:/data
    environment:
      - PUID=33
      - PGUID=33
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
    labels:
      - traefik.http.routers.passwords.rule=Host(`passwords.${DOMAIN_JS}`)
      - traefik.http.routers.passwords.tls=true
      - traefik.http.routers.passwords.tls.certresolver=le
      - traefik.http.routers.passwords.entrypoints=https
    networks:
      - external

networks:
  external:
    external: true
```
Persistent data location:
```
ls -l bitwarden/
total 196
-rw-r--r-- 1 root root 151552 Aug 13 21:39 db.sqlite3
-rw-r--r-- 1 root root  32768 Aug 13 21:44 db.sqlite3-shm
-rw-r--r-- 1 root root      0 Aug 13 21:44 db.sqlite3-wal
drwxr-xr-x 2 root root   4096 Aug 11 23:57 icon_cache
-rw------- 1 root root   1194 Aug 11 23:57 rsa_key.der
-rw------- 1 root root   1679 Aug 11 23:57 rsa_key.pem
```

### SOLUTION
My ZFS pool wasn't loaded correctly, therefore Bitwarden wasn't able to accesss the correct database and created an empty one. My bad, sorry for the hassle :/
