### ISSUE TITLE
Store built binaries in the release assets

### ISSUE THREAD

**Issue by GerardoGR** [dani-garcia/bitwarden_rs#1161]
For convenience it would be nice to have the pre-built binaries in the Github release assets.

I've seen that there is **Release** github action for uploading the asset, but this doesn't get triggered:

```
    - name: Release
      uses: Shopify/upload-to-release@1.0.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: bitwarden_rs-${{ matrix.db-backend }}-${{ matrix.target }}${{ matrix.ext }}
        path: target/${{ matrix.target }}/release/bitwarden_rs${{ matrix.ext }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```
