### ISSUE TITLE
Error can't connect to postgres while restarting containers

### ISSUE THREAD

**Issue by e-belair** [dani-garcia/bitwarden_rs#1168]
### Subject of the issue
When I restart containers, I'm getting the following error:
`[panic][ERROR] thread 'main' panicked at 'Can't connect to DB: BadConnection("FATAL:  the database system is starting up\n")'`

### Your environment
* Bitwarden_rs version: 2.15.1 postgres
* Install method: docker compose
* Other relevant information: 

```
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server-postgresql:latest
    container_name: bitwarden
    env_file:
      - .env
    volumes:
      - bitwarden-data:/data
    restart: "always"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.rule=Host(`${SERVER_NAME}`)"
      - "traefik.http.routers.bitwarden.entrypoints=https"
      - "traefik.http.routers.bitwarden.tls.certresolver=myresolver"
    networks:
      - postgres
      - webproxy

  db:
    container_name: bitwarden_db
    image: postgres
    environment:
      - POSTGRES_USER=bitwarden
      - POSTGRES_PASSWORD=bitwarden
      - POSTGRES_DB=bitwarden
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data/
    labels:
      - "traefik.enable=false"

networks:
  postgres:
    driver: bridge
  webproxy:
    external: true

volumes:
  bitwarden-data:
  db:
```

### Steps to reproduce
`docker-compose restart`

### Expected behaviour
bitwarden should wait for database ready

### Actual behaviour
It tries to connect while database is starting up
