### ISSUE TITLE
Bitwarden_rs Docker image uses confusingly identical Vault code without de/re-branding

### ISSUE THREAD

**Issue by taikedz** [dani-garcia/bitwarden_rs#118]
## Problem

Bitwarden_rs seems to implement the features and interface of original Bitwarden to the exact detail, even parts that don't belong there, like billing pages and copyright notices attributed to `8bit Solutions LLC`

## Environment

I'm running a bitwarden server using the instructions in the README.md of this project, namely using the `mprasil/bitwarden:latest` image.

```yaml
version: "2.2"

services:
  bitwarden:
    image: mprasil/bitwarden:latest
    volumes:
      - "bitwarden:/bitwarden"
    environment:
      - SIGNUPS_ALLOWED=false
      - DATA_FOLDER=/bitwarden
    networks:
      - web
    restart: unless-stopped

volumes:
  bitwarden:

networks:
  web:
    external: true
```

## Description

I notice that all the Copyright notices at the bottom of the pages refer to `8bit Solutions LLC` even though the project is formally unassociated at all, and is a re-write...

This can be cause of confusion, and would seem to be a misrepresentation, unless there's a reason?

Additionally, features like Organizations seem to behave like the original for no valid reason e.g. #96 ; the implementation in the web vault should probably not infer the need for any account levels at all, nor look like they're trying to "call home" for billing purposes.
