### ISSUE TITLE
Remote MySQL Connection drops and never comes back

### ISSUE THREAD

**Issue by misilot** [dani-garcia/bitwarden_rs#1204]
### Subject of the issue
Connection to remote mysql just drops for some reason and never comes back

### Your environment

* Bitwarden_rs version:

* Install method: Docker Compose
* Reverse proxy and version: Apache 2.4.29
* Version of mysql/postgresql: 
* Other relevant information:

### Steps to reproduce

My connection string in docker-compose.yml
      DATABASE_URL: "mysql://bitwarden_rs:password@mysql.example.net:53306/bitwarden_rs"

### Expected behaviour

Connect all happy as can be?

### Actual behaviour

Eventually runs if I do docker compose down; docker compose up -d

### Relevant logs

bitwardenrs    | [2020-10-28 09:40:17.254][r2d2][ERROR] Unknown MySQL server host 'mysql.server.net' (-3)

After restarting I see this. I have to do a complete down and up to get bitwarden_rs working again.
bitwardenrs    | [2020-10-28 12:55:10.450][bitwarden_rs::util][WARN] Can't connect to database, retrying: DieselConError.
bitwardenrs    | [CAUSE] BadConnection(
bitwardenrs    |     "Unknown MySQL server host \'mysql.server.net\' (-3)",
bitwardenrs    | )

**Comment by dani-garcia** [comment]
So restarting bitwarden_rs doesn't fix it, you need to restart the whole docker compose group? Sounds some kind of networking issue in docker, can you share your compose file?

**Comment by misilot** [comment]
```yaml
#---
#Docker-compose file for Bitwarden_rs
#---
version: "3"
services:
  bitwardenrs:
    restart: always
    # Dani Garcia image https://github.com/dani-garcia/bitwarden_rs
    image: "bitwardenrs/server:latest"
    container_name: bitwardenrs
    environment:
      # Timezone settings, important for Fail2ban to work
      TZ: 'America/Chicago'
      # Logging connection attemps
      LOG_FILE: '/data/bitwarden.log'
      EXTENDED_LOGGING: 'true'
      LOG_LEVEL: 'warn'
      # Beef up a bit
      ROCKET_WORKERS: 20
      WEBSOCKET_ENABLED: 'true'
      # Hardening a bit
      SIGNUPS_ALLOWED: 'false'
      ADMIN_TOKEN: '<removed>'
      DOMAIN: 'https://key.domain'
      SHOW_PASSWORD_HINT: 'false'
      DISABLE_ICON_DOWNLOAD: 'true'
      SMTP_HOST: 'apprelay.smtp.domain'
      SMTP_PORT: 25
      SMTP_SSL: 'false'
      SMTP_FROM: 'adm@domain'
      SMTP_FROM_NAME: 'IT'
      DUO_IKEY: 'dafsdf'
      DUO_SKEY: 'fasfsad'
      DUO_HOST: 'api-.duosecurity.com'
      INVITATION_ORG_NAME: 'Password Management'
      ORG_CREATION_USERS: 'libadm@domain'
    networks:
      - bitwarden_net
    ports:
      - '9080:80'
      - '9082:3012'
    volumes:
      - "/klib/data/bw-data:/data"

volumes:
  Certfiles:

networks:
  bitwarden_net:
```

DATABASE_URL: "mysql://bitwarden_rs:password@mysql.example.net:53306/bitwarden_rs"  was in there as well, but I had to switch to sqlite backend for now. 

We did end up removing the networks: bitwarden_net configuration currently as well trying to troubleshoot #1203
