### ISSUE TITLE
Error when logging in bitwarden using Android client.

### ISSUE THREAD

**Issue by benzBrake** [dani-garcia/bitwarden_rs#1209]
### Subject of the issue
Cannot loggin to my bitwarden server with Bitwarden Android 2.6.0 with error message  `Exception Message: Chain validation failed`.

### Your environment

* Bitwarden_rs version: Docker image id 4f627c5a63f0

* Install method: Docker
* Clients used: Bitwarden Android 2.6.1
* Reverse proxy and version: Caddy 1.0.4
* SSL certificate: Let's Encrypt Elliptic Curve 256 2020-12-08
* Other relevant information: I tried to logging on my iPad, there's no problem.

### Steps to reproduce

Using docker-compose, my config is
```
  bitwarden:
    image: bitwardenrs/server 
    container_name: bitwarden
    restart: always
    volumes:
      - /data/bitwarden:/data/bitwarden
    env_file:
      - /data/bitwarden/config.env
```
Conent of config.env
```
SIGNUPS_ALLOWED=false
DOMAIN=http://localhost
DATABASE_URL=/data/bitwarden/database.db
ROCKET_WORKERS=10
WEB_VAULT_ENABLED=true
```
I'm using caddy 1.0.4 for reserve proxy.
Config of caddy
```
mydomain {
    tls webmaster@mydomain
    #rewrite / {
    #    if_op or
    #    if {>User-Agent} not_has "Bitwarden"
    #    if {>User-Agent} not_has "Waterfox"
    #    to /404.html
    #}
    proxy /notifications/hub/negotiate bitwarden:80 {
        transparent
    }
    proxy /notifications/hub bitwarden:3012 {
        websocket
    }
    proxy / bitwarden:80 {
        transparent
    }
}
```
