### ISSUE TITLE
Cannot accept user to an organization using docker image

### ISSUE THREAD

**Issue by ahaw** [dani-garcia/bitwarden_rs#1478]
When I try to approve the user I get the error message "An error has occurred.
An unexpected error has occurred.". 
I was able to approve a single user but nothing after it.

I tried to check logs but nothing I don't see there anything relevant.

My docker compose file:
```
 bitwarden:
#  entrypoint: ["echo", "Service bitwarden disabled"]
  restart: always
  container_name: bitwarden
  image: bitwardenrs/server:alpine
  hostname: bitwarden
  volumes:
   - ./bitwarden/:/data/
  environment:
   - WEBSOCKET_ENABLED=false
   - SIGNUPS_ALLOWED=false
   - ADMIN_TOKEN=<token>
   - DOMAIN=https://mydomain.com/bw
   - LOG_LEVEL=trace
   - EXTENDED_LOGGING=true

```
Im also using envoy proxy to forward https traffic (no wss proxying as I thought it's unneded)
