### ISSUE TITLE
Send feature `try it now` link not working with a subpath.

### ISSUE THREAD

**Issue by reinob** [dani-garcia/bitwarden_rs#1555]
I have just upgraded my docker image to 1.20.0 (:latest), and noticed the new "Bitwarden Send" box shown on the upper right corner.

If I click on "try it now" it goes to _https://$HOST/#/sends_, instead of _https://$HOST/**vault/**#/sends_, which is what I would expect because I have set _DOMAIN=https://$HOST/**vault**_

Note that if I correct the URL manually it goes to the right page (I see the "Create New Send" button, etc.)
Note that I have not tested further, since I still have to learn about this new feature.

PS: I have another BitwardenRS instance with no sub-path and there it works like a charm! :)

**Comment by zamuz** [comment]
To add to this, when downloading a file from a Send, the URL for the download (not the share link) is also missing the subpath and therefore the download fails. When clicking the Download button, the URL that the browser attempts to download looks like this (notice the missing subpath):

https://domain.tld/sends/e26bae02-1a6b-4105-86e2-b7cbb73730c5/e145fa1a25cc300e2e5234d9614a47003892d17b1f27cb9fed377fd0defe5572

**Comment by reneploetz** [comment]
I can only confirm the first issue: The "try it now"-link is indeed broken, but they are hardcoded in the upstream webapp.

But I can create / share / download all sends via browser / (firefox) browser extension and mobile (ios) app with "DOMAIN=https://example.com/bitwarden" using the docker behind an Apache Proxy like below:

```
        RewriteRule ^/bitwarden$ /bitwarden/ [R]
        <LocationMatch ^/(?:bitwarden).*>
            ProxyPass http://127.0.0.1:8085

            RequestHeader set X-Real-IP %{REMOTE_ADDR}s
            RequestHeader set X-Forwarded-Proto "https"

            RewriteCond %{REQUEST_URI} ^/bitwarden/notifications/hub [NC]
            RewriteCond %{HTTP:Upgrade} =websocket [NC]
            RewriteRule /bitwarden/notifications/hub(.*) ws://127.0.0.1:8086%{REQUEST_URI} [P,L]
        </LocationMatch>
```

My docker-compose configuration looks like this (somewhat simplified for brevity - binding the internal bitwarden http server to port 3011 is still shown, using an external database should not be relevant):
```
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    ports:
      - "127.0.0.1:8085:3011"
      - "127.0.0.1:8086:3012"
    restart: always
    environment:
      - DOMAIN=https://example.com.de/bitwarden
      - ROCKET_PORT=3011
      - WEBSOCKET_ENABLED=true
    volumes:
      - data/:/data
```

It appears that the urls are relative, which means you probably need to access bitwarden with the slash at the end initially to avoid cutting off part of your path. You could try to test a sub-sub-path like "DOMAIN=https://$HOST/my/vault" to see if that's the case (tough I did not test this at all). It might be more of a problem related to the proxy-server configuration.
