### ISSUE TITLE
error: cannot decrypt after pulling latest image

### ISSUE THREAD

**Issue by themightychris** [dani-garcia/bitwarden_rs#232]
When I pull the latest image, I see an error along the lines of "cannot decrypt" in place of every item's title. Luckily, reverting back to image `e1509df9617a` fixes the problem. Is there some kind of upgrade/migration step that needs to be done? All I could find in the readme was preserving the /data mount between upgrades

**Comment by mprasil** [comment]
This is certainly weird. I haven't encountered that and I'm using latest image.

Do you have server logs from after the update? Do you use any proxy or websockets or any extra configuration?

**Comment by themightychris** [comment]
I have nginx in front of the container, but that remained constant between my original state, pulling the latest image, and then switching back to the original image

Where would I find the relevant server logs? I do not see anything under `/data` or `/var/log` within the container and did not find anything on logs in the README

I'm launching my instance with this `docker-compose.yml` currently:

```yaml
version: "2"

services:
  web:
    image: e1509df9617a
    restart: always
    environment:
      - SERVER_ADMIN_EMAIL=chris@example.org
    volumes:
      - ./data:/data
    ports:
      - "127.0.0.1:9280:80"
```

If you can point me where to look for the interesting diagnostic data, I can give it another try and see what I can collect
