### ISSUE TITLE
Question: Docker-compose and bitwarden_rs only on RasPi

### ISSUE THREAD

**Issue by MeiRos** [dani-garcia/bitwarden_rs#351]
I'm not sure if this is a good place to talk about this or not. But please. show me other place, if I should change place.

I was about to use bitwarden_rs on VPS but then I decided to move it to my my home network and on Raspberry pi. I had some test settings on VPS which I moved to Rpi. So, I'm going to run this with docker-compose, because settings were quite ready. Is it bad or good idea? There's no need for proxy so there's only Bitwarden image.
I have issued Let's Encrypt certificate with acme.sh. I used DNS alias mode. Maybe this is not needed but now it's secure connection at home. I have to use https://home.example.com to connect securelly.
My docker-compose.yml is:
```
#docker-compose.yml
version: '3'
services:
 bitwarden:
  image: mprasil/bitwarden:raspberry
  restart: always
  volumes:
      - ./bw-data/:/data/
      - /home/pi/ssl/:/ssl/
  environment:
   ROCKET_TLS: '{certs = "/ssl/fullchain.pem", key = "/ssl/key.pem"}'
   SIGNUPS_ALLOWED: "true"
   SMTP_HOST: "smtp.host.net"
   SMTP_FROM: "no-reply@home.example.com"
   SMTP_PORT: "587"
   SMTP_SSL: "true"
   SMTP_USERNAME: "xxx"
   SMTP_PASSWORD: "yyy"
   LOG_FILE: "/data/bitwarden.log"
  ports:
      - 192.168.1.20:443:80 #Raspberry's home IP

```

What do you think? Can this work properly?
If this is ok, I can add this to wiki.
Because I'm noob with docker, how do I update bitwarden image? Just docker-compose down and then up -d ?
