### ISSUE TITLE
Application Config is Env Var Order Dependant

### ISSUE THREAD

**Issue by Mohammed90** [dani-garcia/bitwarden_rs#403]
This is a weird bug that threw me off for a long time. At first I thought it might be related to #359, but now it seems like something else. The docker-compose file here doesn't enable the `/admin` path, despite the ADMIN_TOKEN being set. You'll keep getting 404. It's definitely set because it shows when I ran `env` inside the container.

Here's where it gets freaky, it works if I move the `ADMIN_TOKEN` to the top of the list, i.e. before `ROCKET_PORT`.

```yaml
version: "3"

services:
  bitwarden:
    image: mprasil/bitwarden:latest
    restart: always
    volumes:
      - ./bw-data:/data
    ports:
      - "8080:8080" # Vault portal
      - "3012:3012/tcp" # Websocket
    environment:
      ROCKET_PORT: "8080"
      WEBSOCKET_PORT: "3012"
      WEBSOCKET_ADDRESS: "0.0.0.0"
      WEBSOCKET_ENABLED: "true" # Required to use websockets
      SIGNUPS_ALLOWED: "true" # set to false to disable signups
      INVITATIONS_ALLOWED: "true"
      ADMIN_TOKEN: "ZQpoXSKWI3ux3sV7AYFwMsN5uplvofXyY/hr1Uofqw0xBsayLXgnxxZepZSiL3Ur" # doesn't work here, but works when put as first item
      SMTP_HOST: [redacted]
      SMTP_FROM: [redacted]
      SMTP_PORT: [redacted]
      SMTP_SSL: "true"
      SMTP_USERNAME: [redacted]
      SMTP_PASSWORD: [redacted]
      SHOW_PASSWORD_HINT: "false"
```

I ran `env` inside the container and the ADMIN_TOKEN variable is set:
```
ROCKET_WORKERS=10
SMTP_SSL=true
SHOW_PASSWORD_HINT=false
HOSTNAME=68b6952df777
WEBSOCKET_ADDRESS=0.0.0.0
SMTP_FROM=[redacted]
SMTP_PASSWORD=[redacted]
WEBSOCKET_PORT=3012
ROCKET_ENV=staging
PWD=/
HOME=/root
WEBSOCKET_ENABLED=true
SMTP_HOST=[redacted]
SIGNUPS_ALLOWED=true
ADMIN_TOKEN=ZQpoXSKWI3ux3sV7AYFwMsN5uplvofXyY/hr1Uofqw0xBsayLXgnxxZepZSiL3Ur
INVITATIONS_ALLOWED=true
ROCKET_PORT=8080
TERM=xterm
SMTP_USERNAME=[redacted]
SHLVL=1
WEB_VAULT_ENABLED=true
SMTP_PORT=587
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```
