### ISSUE TITLE
Websocket Notification Traefik

### ISSUE THREAD

**Issue by budimanjojo** [dani-garcia/bitwarden_rs#453]
Hello, I just migrated from Nginx to Traefik. And everything works perfectly unless my Bitwarden. So, I followed the proxy example from https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples and set WEBSOCKET_ENABLED=true in the env file.
This is what I got from the log:
`[ws::handler][ERROR] WS Error <Protocol>: Unable to parse WebSocket key.`
I can't even access my vault, browser shows this error:
`WebSocket Protocol Error: Unable to parse WebSocket key.`
If I comment out the line:
```
      - "traefik.hub.frontend.rule=Host:vault.jojocomptech.com;Path:/notifications/hub"
      - "traefik.hub.port=3012"
```
in my docker-compose file, then everything is working again except I can't auto sync my data across devices.
This is my docker-compose file (example domain name of course):
```
version: '3.7'

services:
  bitwarden_rs:
    image: "mprasil/bitwarden:latest"
    container_name: "bitwarden_rs"
    restart: always
    env_file:
      - config.env
    volumes:
      - "app:/data"
      - "db:/database"
      - "log:/log"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=bitwarden_rs"
      - "traefik.web.frontend.rule=Host:bitwarden.example.com"
      - "traefik.web.port=80"
      - "traefik.hub.frontend.rule=Host:bitwarden.example.com;Path:/notifications/hub"
      - "traefik.hub.port=3012"
      - "traefik.docker.network=traefik_default"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.customFrameOptionsValue=SAMEORIGIN"

networks:
  traefik:
    external:
      name: traefik_default

volumes:
  app:
  db:
  log:
```
And this is my config.env file (example domain and credentials of course):
```
SIGNUPS_ALLOWED=true
INVITATIONS_ALLOWED=false
WEBSOCKET_ENABLED=true
SHOW_PASSWORD_HINT=false
DOMAIN=https://bitwarden.example.com
DATABASE_URL=/database/bitwarden_rs.sqlite3
ATTACMENTS_FOLDER=/attachments
ICON_CACHE_FOLDER=/icon_cache
LOG_FILE=/log/bitwarden_rs.log
ROCKET_WORKERS=15
WEB_VAULT_ENABLED=true
SMTP_HOST=mail.example.com
SMTP_FROM=me@example.com
SMTP_FROM_NAME=My Name
SMTP_PORT=587
SMTP_SSL=true
SMTP_USERNAME=myname
SMTP_PASSWORD=123456
```
Thanks before :+1:
