### ISSUE TITLE
How to use with nginx reverse proxy container and nginx letsencrypt companion container

### ISSUE THREAD

**Issue by leggettc18** [dani-garcia/bitwarden_rs#469]
I'm attempting to deploy this using a docker_compose file, I already have it hosting a few more service set up in a similar way that work just fine, but for some reason with bitwarden_rs I'm getting a 502 bad gateway when I visit the domain. SSL is working, but I'm not getting to the actual app. Some help would be appreciated, here's the relevant parts of my docker_compose file.
```
version: '3'

services:
  
  bitwarden:
   image: mprasil/bitwarden
   restart: always
   volumes:
     - ./bw-data:/data
   environment:
     SIGNUPS_ALLOWED: "true"
     VIRTUAL_HOST: bitwarden.leggett.dev
     VIRTUAL_PORT: 443
     VIRTUAL_PROTO: https
     LETSENCRYPT_HOST: bitwarden.leggett.dev
     LETSENCRYPT_EMAIL: chris@leggett.dev
   networks:
     - proxy-tier

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier

letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

networks:
  proxy-tier:
```

**Comment by mprasil** [comment]
If I understand letsencrypt companion container configuration correctly (never used it, so I might be wrong here), you might want to remove `VIRTUAL_PORT: 443` from your configuration, because `bitwarden_rs` listens on port `80` by default.

**Comment by leggettc18** [comment]
I still get the bad gateway if I take that out. I also tried changing the Virtual Port to 80, as well as setting the Rocket Port to 443 with Virtual Port to 443.

**Comment by mprasil** [comment]
You also want to remove `VIRTUAL_PROTO: https` if you're not doing https on the `bitwarden_rs` side.

**Comment by leggettc18** [comment]
I did that as well, still getting the bad gateway error.

**Comment by mprasil** [comment]
Any errors in the `bitwarden_rs` container logs?

**Comment by leggettc18** [comment]
Would they be somewhere in the bwdata folder? Or somewhere in the container itself? I'm at work currently but I'll take a look as soon as I can.

**Comment by mprasil** [comment]
The logs are sent to stdout by default, so you should be able to see them with `docker logs`.

**Comment by leggettc18** [comment]
Actually I may have figured it out. It looks like had an incorrectly configured container running that was maybe taking up the port or something? I think it was caused by me renaming the parent directory and attempting to relaunch the containers, not realizing it made new containers. I saw an error and put it back but I didn't realize the containers had been created already. Stopping and removing all containers and relaunching the docker-compose command seems to have fixed it. Thanks for your help!

**Comment by scope-username** [comment]
> Actually I may have figured it out. It looks like had an incorrectly configured container running that was maybe taking up the port or something? I think it was caused by me renaming the parent directory and attempting to relaunch the containers, not realizing it made new containers. I saw an error and put it back but I didn't realize the containers had been created already. Stopping and removing all containers and relaunching the docker-compose command seems to have fixed it. Thanks for your help!

Could you please help me out with docker-compose you have used to get bitwarden_rs container running with nginx reverse proxy container and nginx letsencrypt companion container ? I am getting the same 502 bad gateway error as you did previously and changing the port for bitwarden_rs container didn't help.

**Comment by kdaveid** [comment]
Maybe @leggettc18 can confirm he used the **posted** `docker-compose` file above (or post the current one) to help other users/community. If everything is fine, please close the issue, that helps additionally. Thanks!

**Comment by leggettc18** [comment]
I apologize for just now seeing this. I only have access to my phone for right now, but I'll post my current docker-compose file tomorrow night.

**Comment by leggettc18** [comment]
```
version: '3'

services:
  bitwarden:
    image: mprasil/bitwarden
    restart: always
    volumes:
      - ./bw-data:/data
    environment:
      ADMIN_TOKEN: ********************
      SIGNUPS_ALLOWED: "false"
      VIRTUAL_HOST: cloud.domain.tld
      LETSENCRYPT_HOST: cloud.domain.tld
      LETSENCRYPT_EMAIL: valid@email.com
    networks:
      - proxy-tier

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

networks:
  proxy-tier:


```
Here's the relevant parts of my docker-compose file that are currently working. (Sensitive information edited out, obvs). I don't believe I changed anything between these trys, the problem I had was a previously incorrectly configured container taking the port but not getting routed to properly by the reverse proxy. Check to make sure you don't have any containers still running from failed attempts or previous configurations. Otherwise this setup should work.
