### ISSUE TITLE
docker image bitwardenrs/server-mysql never uses mysql

### ISSUE THREAD

**Issue by maoxuner** [dani-garcia/bitwarden_rs#512]
I have corrected set the envars accordding to wiki [Using the MySQL Backend](https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MySQL-Backend), and bitwarden_rs never connects mysql but always create a sqlite file by DATABASE_URL like `mysql://user:pass@mysql/user_bitwarden`（My database container 's name is `mysql`）.

```
root@bitwarden:/# file mysql\:/user\:pass\@mysql/user_bitwarden 
mysql:/user:pass@mysql/user_bitwarden: SQLite 3.x database, last written using SQLite version 3026000
```

Part of the docker-compose file
```
version: "3"
serevices:
  bitwarden:
    container_name: bitwarden
    hostname: bitwarden
    image: bitwardenrs/server-mysql:${BITWARDEN_TAG:-latest}
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    restart: always
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
      ADMIN_TOKEN: admin
      DATABASE_URL: "mysql://user:pass@mysql/user_bitwarden"
      ENABLE_DB_WAL: "false"
    networks:
      - underlay
      - database
networks:
  underlay:
  database:
```

I tried build the image for myself following [Building your own image](https://github.com/dani-garcia/bitwarden_rs/wiki/Building-your-own-image).
```
docker build -t bitwarden_rs --build-arg DB=mysql .
```
Then it works well. So I suppose there may be a wrong build argument with the image `bitwardenrs/server-mysql`.
