### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by p3lim** [dani-garcia/bitwarden_rs#537]
Attempting to use [Fastmail](https://www.fastmail.com/help/technical/servernamesandports.html) for SMTP, and syncing users from LDAP following the [wiki page](https://github.com/dani-garcia/bitwarden_rs/wiki/Syncing-users-from-LDAP).

Here's my (redacted) compose file:
```yaml
version: '3'
services:
  bitwarden:
    image: bitwardenrs/server:1.9.1
    restart: always
    volumes:
      - ./bw-data:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - SMTP_HOST=smtp.fastmail.com
      - SMTP_FROM=foo@fastmail.com
      - SMTP_PORT=465
      - SMTP_SSL=true
      - SMTP_USERNAME=foo@fastmail.com
      - SMTP_PASSWORD=bar
      - DOMAIN=https://bitwarden.example.com
      - ADMIN_TOKEN=baz
  ldap:
    image: vividboarder/bitwarden_rs_ldap:latest
    restart: always
    depends_on:
      - bitwarden
    volumes:
      - ./ldap.toml:/config.toml:ro
    environment:
      - CONFIG_PATH=/config.toml
```

When the ldap service attempts an invite it timeouts, with bitwarden_rs throwing the following error:

```
[bitwarden_rs::error][ERROR] Error sending email. Complete
```

Is there any way to get more information than that, what exactly went wrong?
