### ISSUE TITLE
502 Bad Gateway /  jwilder/nginx-proxy

### ISSUE THREAD

**Issue by Jerome2103** [dani-garcia/bitwarden_rs#581]
Hello everybody

I need help.
I have set up bitwarden, and now comes a 502 error.

Do not see the mistake, have already tried different.

Thanks in advance.

config.yml
```# 
# Note: After making changes to this file you need to run the `rebuild` or `update`
# command for them to be applied.
# 
# Full URL for accessing the installation from a browser. (Required)
url: https://host.xyz
# 
# Auto-generate the `./docker/docker-compose.yml` config file.
# WARNING: Disabling generated config files can break future updates. You will be
# responsible for maintaining this config file.
# Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/DockerCompose.hbs
generate_compose_config: true
# 
# Auto-generate the `./nginx/default.conf` file.
# WARNING: Disabling generated config files can break future updates. You will be
# responsible for maintaining this config file.
# Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/NginxConfig.hbs
generate_nginx_config: true
# 
# Docker compose file port mapping for HTTP. Leave empty to remove the port mapping.
# Learn more: https://docs.docker.com/compose/compose-file/#ports
http_port: 8000
```

And here the docker-compose.override.yml file:
docker-compose.override.yml
```
version: '3'
services:
 nginx:
    ports:
      - 8000
    environment:
      - VIRTUAL_HOST=host.xyz
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=host.xyz
      - LETSENCRYPT_EMAIL=email
    networks:
      webproxy:

networks:
  webproxy:
    external:
      name: nginx-proxy
```
