### ISSUE TITLE
Changing the image

### ISSUE THREAD

**Issue by ITHanke** [dani-garcia/bitwarden_rs#680]
Hi Guys,

I need some help with the docker image. Some options i want is to have:
- Disable registration of new users
- Enabling YubiKey OTP authentication

But where and when i put these command? At getting the docker file? Or in the bash of the docker image what is running?

**Comment by fbartels** [comment]
A lot of the configuration is done through environment variables. The available options are documented at https://github.com/dani-garcia/bitwarden_rs/blob/master/.env.template

**Comment by Brice187** [comment]
Or you can use docker-compose.yml to set environment vars:

```
version: '2'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: always
    environment:
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=PLEASEUSEASTRONGTOKEN
      - DOMAIN=https://passwords.example.com
    volumes:
      - ./data/:/data/
    networks:
      frontend:
    labels:
      - "traefik.backend=bitwarden"
      - "traefik.docker.network=traefik_frontend"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:passwords.example.com"
      - "traefik.frontend.headers.contentSecurityPolicy=default-src 'self'; script-src 'self'; style-src 'self' ; object-src 'none'; frame-ancestors 'self'; form-action 'none'; base-uri 'self'"

networks:
  frontend:
    external:
      name: traefik_frontend
```
