### ISSUE TITLE
Websocket with Traefik and docker compose

### ISSUE THREAD

**Issue by sesshomaru86** [dani-garcia/bitwarden_rs#740]
Hello guys, 

i cant achieve to make the websocket  to work. If i try to open https://domain.com/notifications/hub i'm getting the error "Internal Server Error" .If i change the label from ws to wss same error.

i don't know if it helps but i can see these errors too in the browser

``

X-Firefox-Spdy | h2
-- | --
access-control-allow-origin |  
cache-control | no-cache, no-store, max-age=0
cf-cache-status | DYNAMIC
cf-ray | 53b5ef0979acd111-TXL
content-length | 385
content-security-policy | frame-ancestors 'self' chrome-extension://nngceckbapebfimnlniiiahkandclblb moz-extension://*;
content-type | application/json
date | Mon, 25 Nov 2019 19:12:22 GMT
expect-ct | max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
feature-policy | accelerometer  'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none';  encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope  'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment  'none'; picture-in-picture 'none'; sync-xhr 'self'  https://haveibeenpwned.com https://twofactorauth.org; usb 'none'; vr  'none'
referrer-policy | same-origin
server | cloudflare
x-content-type-options | nosniff
x-frame-options | SAMEORIGIN
x-xss-protection | 1; mode=block

``
Also from what i read Cloudflare SSL fully supports WebSockets traffic passing through their network so it shouldn't be an issue. 

In the raw data i can see this 
```
{"ErrorModel":{"Message":"'/notifications/hub' should be proxied to the websocket server or notifications won't work. Go to the README for more info.","Object":"error"},"Message":"","Object":"error","ValidationErrors":{"":["'/notifications/hub' should be proxied to the websocket server or notifications won't work. Go to the README for more info."]},"error":"","error_description":""}
```
and in the logs 

```

[2019-11-25 19:12:16][_][INFO] Matched: GET /notifications/hub (websockets_err)
[2019-11-25 19:12:16][bitwarden_rs::error][ERROR] '/notifications/hub' should be proxied to the websocket server or notifications won't work. Go to the README for more info.. '/notifications/hub' should be proxied to the websocket server or notifications won't work. Go to the README for more info.
[2019-11-25 19:12:16][_][INFO] Outcome: Success
[2019-11-25 19:12:16][_][INFO] Response succeeded.
[2019-11-25 19:12:22][rocket::rocket][INFO] GET /notifications/hub text/html:
[2019-11-25 19:12:22][_][INFO] Matched: GET /notifications/hub (websockets_err)
[2019-11-25 19:12:22][bitwarden_rs::error][ERROR] '/notifications/hub' should be proxied to the websocket server or notifications won't work. Go to the README for more info.. '/notifications/hub' should be proxied to the websocket server or notifications won't work. Go to the README for more info.
[2019-11-25 19:12:22][_][INFO] Outcome: Success

```

```

  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    restart: always
    ports:
     - "3300:80"
    networks:
      - traefik_proxy
    volumes:
      - ./bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
      ADMIN_TOKEN: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
      SMTP_HOST: 'smtp.gmail.com'
      SMTP_FROM: 'bitwarden@domaincom'
      SMTP_PORT: '587'
      SMTP_SSL: 'true'
      SMTP_USERNAME: 'blabla@gmail.com'
      SMTP_PASSWORD: 'xxxxxxxxxxxxxxxxxxxxxx'
      DOMAIN: 'https://bitwarden.domain.com'
      LOG_FILE: '/data/log'
      EXTENDED_LOGGING: 'true'

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.web.frontend.rule=Host:bitwarden.domain.com"
      - "traefik.web.port=80"
      - "traefik.hub.frontend.rule=Host:bitwarden.domain.com;Path:/notifications/hub"
      - "traefik.hub.port=3012"
      - "traefik.hub.protocol=ws"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=bitwarden.domain.com"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.frontend.headers.frameDeny=true"


```
 

Any idea ? Thanx !
