### ISSUE TITLE
Unhealthy container

### ISSUE THREAD

**Issue by STaRDoGG** [dani-garcia/bitwarden_rs#795]
#713 # Subject of the issue
My container is showing as "Unhealthy"; restarting the container seems to have no effect, as it will always still show as unhealthy.

![image](https://user-images.githubusercontent.com/1524526/71656406-aa61af80-2d00-11ea-9fd8-52b2b241bfbb.png)

### Your environment

* Bitwarden_rs version: 

![image](https://user-images.githubusercontent.com/1524526/71656441-d2511300-2d00-11ea-9a79-bec76453c88d.png)

* Install method:  Docker image using compose.

```
version: '2'

# https://hub.docker.com/r/bitwardenrs/server

services:

  bitwarden:
    container_name: bitwarden
    image: 'bitwardenrs/server:latest'
    environment:
      - TZ='America/Chicago'
      - PUID=197609
      - PGID=197121
    restart: unless-stopped
    volumes:
      - 'scotts_bitwarden_data:/data'
    ports:
        - '9069:80'
    networks:
      - om

networks:
  om:
    external:
      name: oly-misc
```

* Reverse proxy and version: Nginx
* Version of mysql/postgresql:  N/A

### Steps to reproduce

Just with the above compose code, and once created, just the standard start/stop commands.

### Expected behaviour

A **healthy** container. ;P

### Actual behaviour

An **unhealthy** container ;P

### Relevant logs

Looking at the main log it shows nothing of interest related to errors, etc. If there's another log to view that may provide better info, lemme know and I'll post it.

**Comment by mprasil** [comment]
That sounds like health check failing for whatever reason or maybe container being reported as unhealthy before first health check returning success.

Can you docker exec health check manually and see if that works?

**Comment by STaRDoGG** [comment]
> Can you docker exec health check manually and see if that works?

Sorry, I'm still learning my way around Docker and not familiar with manually running a health check; can you save me a bit of time digging up the command to do it?

**Comment by mprasil** [comment]
Ah apologies. So you can `docker exec <container name> <command>` commands inside container:

```bash
docker exec -ti bitwarden healthcheck.sh
```

You can also try running `curl` directly for some extra verbosity:

```bash
docker exec -ti bitwarden curl -v http://localhost:80/alive
```

**Comment by STaRDoGG** [comment]
Thanks @mprasil, I appreciate it.

Trying to run:

```shell
docker exec -ti bitwarden healthcheck.sh
```

Just gives me:

> OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"healthcheck.sh\": executable file not found in $PATH": unknown

and:

```shell
 docker exec -ti bitwarden curl -v http://localhost:80/alive
```

> curl: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libidn2.so.0: file too short

I should mention that I'm running Docker Desktop on Win 10, in case it helps.

**Comment by mprasil** [comment]
Hmm, looks like for some reason the `curl` fails to run in windows docker. I currently have no way of testing how that behaves, but as a quick workaround, you can disable health check.

For your docker compose:

```yaml
version: '2'

# https://hub.docker.com/r/bitwardenrs/server

services:

  bitwarden:
    container_name: bitwarden
    image: 'bitwardenrs/server:latest'
    environment:
      - TZ='America/Chicago'
      - PUID=197609
      - PGID=197121
    restart: unless-stopped
    volumes:
      - 'scotts_bitwarden_data:/data'
    ports:
        - '9069:80'
    networks:
      - om
    healthcheck:
      disable: true

networks:
  om:
    external:
      name: oly-misc
```
