### ISSUE TITLE
docker-compose and [rocket::config::error][ERROR] I/O error while setting tls.certs:

### ISSUE THREAD

**Issue by blotsome** [dani-garcia/bitwarden_rs#806]
### Subject of the issue
Converting a docker run container that works to docker-compose yields this [rocket::config::error][ERROR] I/O error while setting tls.certs:

### Your environment

* Bitwarden_rs version: latest

* Install method: docker-compose
* Clients used: 
* Reverse proxy and version:  self-signed certificate on lan via IP address

### Steps to reproduce
Here is the docker code that works:
```
docker run -d \
	--name='bitwarden' \
	-e 'SIGNUPS_ALLOWED'='true' \
	-e ROCKET_TLS='{certs="/ssl/certificate.crt",key="/ssl/private.key"}' \
	-p 8343:80/tcp \
	-v /data/bw/:/data/:rw \
	-v /ssl/:/ssl/ \
	bitwardenrs/server:latest
```
and here is the docker-compose.yml that does not work:
```
version: '3'
services:
  bitwarden:
    image: bitwardenrs/server
    volumes:
      - /data/bw:/data
      - /ssl:/ssl
    ports:
      - 8343:80
    environment:
      SIGNUPS_ALLOWED: 'true'
      ROCKET_TLS: '{certs = "/ssl/bitwarden.crt", key = "/ssl/bitwarden.key"}'
      LOG_FILE: '/data/bitwarden.log'
    restart: unless-stopped
```

I've tried adding and removing quotes from the rocket_tls file. I've tried changing the permission of those two ssl files. from 600 to 644. Well the .crt is 644, and the key is 600, and i change key to 644 for testing purposes. I also tried creating a new, blank mnt instead of reusing the mnt point that worked in the docker run command. 
### Expected behaviour

Create a healthy, running docker the same as the docker run command.
### Actual behaviour

Keeps restarting over and over, and showing the errors below.
### Relevant logs

I see 
```
bitwarden_1  | [2020-01-07 03:21:10][rocket::config::error][ERROR] I/O error while setting tls.certs:
bitwarden_1  | Logger failed to initialize: attempted to set a logger after the logging system was already initialized
```
and once it restarts, it just says `docker_bitwarden_1 exited with code 1`
