### ISSUE TITLE
`DATABASE_URL` is meant for MySQL or Postgres, while this server is meant for SQLite

### ISSUE THREAD

**Issue by mzch** [dani-garcia/bitwarden_rs#860]
### Subject of the issue

Container can't access to PostgreSQL server.

### Your environment

* Bitwarden_rs version: latest
* Install method: docker
* Version of mysql/postgresql: PostgreSQL 11.6

### Steps to reproduce

- docker-compose up
docker-compose.yml is as below:
```yaml
version: '3.3'
services:
  application:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    ports:
      - 8080:80
      - 3012:3012
    volumes:
      - /srv/bitwarden/data:/data
    environment:
      - DATABASE_URL=postgresql://bitwarden:password@192.168.207.11:5432/bitwarden?sslmode=disable
      - ENABLE_DB_WAL=false
      - WEBSOCKET_ENABLED=true
      - WEBSOCKET_ADDRESS=0.0.0.0
      - WEBSOCKET_PORT=3012
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - DOMAIN=https://bitsteward.com
      - SMTP_HOST=mx1.mail-services.net
      - SMTP_FROM=no-repky@bitsteward.com
      - SMTP_FROM_NAME=BitSteward
      - SMTP_PORT=465
      - SMTP_SSL=true
      - SMTP_USERNAME=admin@example.com
      - SMTP_PASSWORD=password
      - SMTP_AUTH_MECHANISM="Plain"
      - SMTP_TIMEOUT=15
```
### Expected behaviour

Bitwarden_rs starts normally.

### Actual behaviour

Abort.

### Relevant logs

```log
Feb 13 02:27:58 n21 docker-compose[15501]: #033[36mbitwarden      |#033[0m Error loading config:
Feb 13 02:27:58 n21 docker-compose[15501]: #033[36mbitwarden      |#033[0m #011`DATABASE_URL` is meant for MySQL or Postgres, while this server is meant for SQLite
```
