### ISSUE TITLE
Cannot read property 'importKey' of null

### ISSUE THREAD

**Issue by Etelis2019** [dani-garcia/bitwarden_rs#872]
I run bitwarden on ubuntu 18.4 aws , now I understand that I need HTTPS in order to run this on chrome or use chrome expansion.

I went to the wiki but I couldnt figure out how to make the connection HTTPS I mean, please can you direct me to a method that explains how to do SSL certification on that docker container.

sorry about the noob question

**Comment by Gasur** [comment]
You should probably look at running a reverse proxy, especially if you run more websites. If you only use Docker, I would recommend Traefik as it is super easy to set up. Else Caddy is very user friendly too.

**Comment by Etelis2019** [comment]
> You should probably look at running a reverse proxy, especially if you run more websites. If you only use Docker, I would recommend Traefik as it is super easy to set up. Else Caddy is very user friendly too.

Hey thank you so much for the reply. 
I have installed Traefik, set it up using this guide https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-18-04

Also combined the domain I bought with the AWS dns of my server 
so now I have the subdomain monitor.myserver.club running and it is SSL, and I have also bitwarden installed on the docker, but how do I combine them so the bitwarden runs through Traefik?
I really do try to understand and find but I cannot figure that out :(

**Comment by dennisgerding** [comment]
Dear @Etelis2019, it looks like you have Traefik up and running. Good job! Now you should add the proper labels to your bitwarden container so Traefik knows what to do. You can find an example of that [here](https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples). I'll also post my ```docker-compose.yml``` below so you have another example. Hope it helps! 

```
version: '2.0'

services:
  bitwarden_rs:
    image: bitwardenrs/server:alpine
    container_name: bitwarden_rs
    restart: always
    volumes:
      - /opt/docker/bitwarden_rs/bw-data:/data
    networks:
      - proxy
    environment:
      LOG_FILE: '/data/bitwarden.log'
      LOG_LEVEL: 'warn'
      EXTENDED_LOGGING: 'true'
      WEBSOCKET_ENABLED: 'true'
    labels:
      - "traefik.enable=true"
## TRAEFIK VAULT ##
      - "traefik.http.routers.bitwarden-secure.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`vault.domain.nl`)"
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.routers.bitwarden-secure.tls.certresolver=http"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden"
      - "traefik.http.routers.bitwarden-secure.middlewares=security-headers@file"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
## TRAEFIK ADMIN ##
      - "traefik.http.routers.bitwarden-secure-admin.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure-admin.rule=Host(`vault.domain.nl`) && Path(`/admin`)"
      - "traefik.http.routers.bitwarden-secure-admin.tls=true"
      - "traefik.http.routers.bitwarden-secure-admin.tls.certresolver=http"
      - "traefik.http.routers.bitwarden-secure-admin.service=bitwarden-admin"
      - "traefik.http.routers.bitwarden-secure-admin.middlewares=sysop-auth@file,security-headers@file"
      - "traefik.http.services.bitwarden-admin.loadbalancer.server.port=80"
## TRAEFIK WEBSOCKET ##
      - "traefik.http.routers.bitwarden-secure-websocket.rule=Host(`vault.domain.nl`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-secure-websocket.entrypoints=https"
      - "traefik.http.routers.bitwarden-secure-websocket.tls=true"
      - "traefik.http.routers.bitwarden-secure-websocket.tls.certresolver=http"
      - "traefik.http.routers.bitwarden-secure-websocket.service=bitwarden-websocket"
      - "traefik.http.routers.bitwarden-secure-websocket.middlewares=security-headers@file"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
## TRAEFIK NETWORK ##
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```
