### ISSUE TITLE
Docker-compose with nginx for raspberry pi

### ISSUE THREAD

**Issue by MeiRos** [dani-garcia/bitwarden_rs#880]
I'm still studying Docker and if there are pros who have some spare time, it would be nice if you can read through my setup and say something about it. Thank You! :)

docker-compose.yml
```
#docker-compose.yml
version: '3'
services:
 bitwarden:
  image: bitwardenrs/server:raspberry
  restart: always
  volumes:
      - ./bw-data/:/data/
  environment:
   WEBSOCKET_ENABLED: 'true' # Required to use websockets
   SIGNUPS_ALLOWED: 'true'
   DOMAIN: 'https://home.domain'
   SMTP_HOST: "smtp.net"
   SMTP_FROM: "no-reply@home.domain"
   SMTP_PORT: "587"
   SMTP_SSL: "true"
   SMTP_USERNAME: "apikey"
   SMTP_PASSWORD: "xxyyyzzbbccdd"
   LOG_FILE: "/data/bitwarden.log"
   LOG_LEVEL: "warn"
   TZ: "Europe/xxx"
 nginx-proxy:
  container_name: nginx-proxy
  image: nginx:mainline-alpine
  restart: always
  ports:
      - 80:80
      - 443:443
  volumes:
      - /home/pi/nginx/:/etc/nginx/conf.d # Site.conf goes here
      - /home/pi/ssl/:/etc/ssl/private/ # Certificate goes here
```

mysite.conf **(edited this file)**
```
server {
  listen 443 ssl http2;
  server_name home.domain;
  server_tokens off;

  # Specify SSL config if using a shared one.
  #include conf.d/ssl/ssl.conf;
  ssl_certificate     /etc/ssl/private/fullchain.pem;
  ssl_certificate_key /etc/ssl/private/key.pem;
  ssl_protocols       TLSv1.3 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA512:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:ECDH+AESGCM:ECDH+AES256:DH+AESGCM:DH+AES256:RSA+AESGCM:!aNULL:!eNULL:!LOW:!$

  proxy_buffers 16 16k;
  proxy_buffer_size 16k;
  proxy_max_temp_file_size 0;

  # Allow large attachments
  client_max_body_size 128M;

  location / {
    proxy_pass http://bitwarden:80;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /notifications/hub {
    proxy_pass http://bitwarden:3012;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location /notifications/hub/negotiate {
    proxy_pass http://bitwarden:80;
  }

  # Optionally add extra authentication besides the AUTH_TOKEN
  # If you don't want this, leave this part out
  location /admin {
    # See: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
  #  auth_basic "Private";
  #  auth_basic_user_file /path/to/htpasswd_file;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://bitwarden:80;
    allow 192.168.1.1/16;
    deny all;
  }

}
```

Mysite.conf is mostly taken from the Wiki. It's Shauder's proxy example. I did some modifications.
I had warnings in the log. `2020/02/26 17:22:32 [warn] 7#7: *33 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/01/0000000011 while reading upstream, client: 192.168.1.25, server: home.domain, request: "GET /fonts/Open_Sans-normal-400.woff HTTP/2.0", upstream: "http://192.168.144.20:80/fonts/Open_Sans-normal-400.woff", host: "home.domain", referrer: "https://home.domain/app/main.bedb15f54ccaf67e0102.css"` I tried first to add buffer sizes to 16k, but it didn't help. Then I add temp file size to 0. No more warnings.

If this looks good to everybody, I'd like to add this to Wiki. With this guide you can install Bitwarden_rs and nginx proxy very easily on Raspberry pi.

I use acme.sh to get certificates.
