### ISSUE TITLE
Unable to get attachments and websocket working w/ nginx reverse proxy

### ISSUE THREAD

**Issue by gxgani** [dani-garcia/bitwarden_rs#947]
```
bitwarden_rs: Version 1.14.1-843604c9 
os: debian 10.3
Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.25.4, build 8d51620a
nginx version: nginx/1.17.8 
```

I've setup bitwarden_rs over nginx reverse proxy with acme.sh certificates for domains. **Unable to** get **attachments** (config.json setup with limits) and **websocket** working.

## Error when accessing web-socket 
```
bitwarden_1  | [2020-04-03 22:31:59][ws::io][INFO] Accepted a new tcp connection from 127.0.0.1:38140.
bitwarden_1  | [2020-04-03 22:31:59][ws::handler][ERROR] WS Error <Protocol>: Unable to parse WebSocket key.
```

Here's my config:

### bitwarden docker-compose.yml
```
version: '3.7'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    restart: always
    network_mode: host
    volumes:
      - ./bitwarden_data:/data
    environment:
      - 'WEBSOCKET_ENABLED=true'
      - 'EXTENDED_LOGGING=true'
      - 'WEBSOCKET_PORT=3012'
      - 'RSA_KEY_FILENAME=data/rsa_key'
      - 'ROCKET_ENV=staging'
      - 'ROCKET_WORKERS=10'
      - 'ROCKET_PORT=8080'
      - 'TZ=${TIME_ZONE}'
      - 'PUID=${PUID}'
      - 'PGID=${PGUID}'
    ports:
      - 8080:8080
      - 3012:3012
    env_file: .env
```

### nginx reverse proxy
```
upstream bitwarden {
  server 127.0.0.1:8080;
}

upstream bitwarden_notification {
  server 127.0.0.1:3012;
}

....
  # Vault / API
  location / {
    proxy_pass http://bitwarden;
    real_ip_header CF-Connecting-IP; # Cloudflare
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;  }

  # WebSocket (Notification System)
  location /notifications/hub {
    proxy_pass http://bitwarden_notification;
    real_ip_header CF-Connecting-IP; # Cloudflare
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP       $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # Override to support negotiation endpoint for above
  location /notifications/hub/negotiate {
    proxy_pass http://bitwarden;
  }
```
PS: Setup **was** behind cloudflare with websockets enabled.
