### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by yodaphone** [dani-garcia/bitwarden_rs#977]
### Subject of the issue
Even after i do a docker pull with  bitwardenrs/server:1.14.2, the version number displays Version 2.13.2 in the application.

What am i doing wrong?

### Your environment

* Bitwarden_rs version: 1.14.2

* Install method: Docker compose

### Steps to reproduce

```
# bitwarden
version: '3'

services:
 bitwarden:
  image: bitwardenrs/server:1.14.2
  container_name: bitwarden
  restart: always
  volumes:
      - /opt/bitwarden/data:/data/
  ports:
    - 8088:80
    - 3012:3012
  environment:
    LOG_FILE: '/opt/bitwarden/bitwarden.log'
    LOG_LEVEL: 'debug'
    EXTENDED_LOGGING: 'true'
    WEB_VAULT_ENABLED: 'true'
    WEBSOCKET_ENABLED: 'true'
    WEBSOCKET_PORT: '3012'
    ADMIN_TOKEN: 'XXXXXXXXXXXXXXX'
    SIGNUPS_ALLOWED: 'true'
```
